### ISSUE TITLE
Two-leaves problem

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/leafy-decorations#1]
Hello, Thomas! Thank you for helping with the last issue) I am still struggling with the mindfulness website, so I decided to move forward and come back to it later.

I have already submitted the leafy-decorations assignment because I could hit all the screenshots, but when I started to play with my browser screen sizing the two leaves image still gets weird and misplaced at some points. I wonder how I can fix that problem.

Thank you once again!

@thomasjbradley

**Comment by thomasjbradley** [comment]
I think the way I solved the problem is that only the green banner image is a CSS background. The two leaves icon is an `<img>` tag within the banner content.

**Comment by anna-pokhilenko** [comment]
It worked, thank you)
